apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: maheshkumarnovice/inventory-backend:latest
        envFrom:
          - configMapRef:
              name: app-config
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: maheshkumarnovice/inventory-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  ports:
  -  port: 5000
     protocol: TCP
     targetPort: 5000
  selector:
    app: backend
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  ports:
  -  port: 3000
     protocol: TCP
     targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: app
data:
  DB_URL: db_url
  APP_SETTINGS: config.dev
  SENDGRID_API_KEY: api_key
  EMAIL_CONFIRMATION_SENDER_EMAIL: email@email.com
  SECRET_KEY: super_secret